# Site settings
title:
email: contato@blueberryfilmes.com.br
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: blueberryfilmes
github_username: blueberryfilmes

# Build settings
markdown: kramdown
